packages:
  - "apps/*"
  - "packages/*"

catalog:
  # tooling
  "@biomejs/biome": "^1.9.0"
  "@turbo/gen": "^2.9.15"
  "turbo": "^2.9.15"
  "typescript": "^6"
  # react
  "react": "^19.2.6"
  "react-dom": "^19.2.6"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  # tailwind
  "@tailwindcss/vite": "^4"
  "tailwindcss": "^4"
  # misc shared
  "@types/node": "^22"
  "lucide-react": "^1.18.0"
